//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M0242")]
        public string MachineID {
            get {
                return ((string)(this["MachineID"]));
            }
            set {
                this["MachineID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string PortRFID {
            get {
                return ((string)(this["PortRFID"]));
            }
            set {
                this["PortRFID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string PortBarcode {
            get {
                return ((string)(this["PortBarcode"]));
            }
            set {
                this["PortBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.131.2.87")]
        public string MonitoringServerIP {
            get {
                return ((string)(this["MonitoringServerIP"]));
            }
            set {
                this["MonitoringServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProductsMod6")]
        public string TableProductsName {
            get {
                return ((string)(this["TableProductsName"]));
            }
            set {
                this["TableProductsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tbl_ResuMachine6")]
        public string TableSensorsName {
            get {
                return ((string)(this["TableSensorsName"]));
            }
            set {
                this["TableSensorsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AssemTrace")]
        public string TraceabilityDBName {
            get {
                return ((string)(this["TraceabilityDBName"]));
            }
            set {
                this["TraceabilityDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qsn.corp.sensata.com")]
        public string ProductsServerIP {
            get {
                return ((string)(this["ProductsServerIP"]));
            }
            set {
                this["ProductsServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MachinesTrace")]
        public string TraceabilityMachinesDBName {
            get {
                return ((string)(this["TraceabilityMachinesDBName"]));
            }
            set {
                this["TraceabilityMachinesDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sensors")]
        public string LocalTableName {
            get {
                return ((string)(this["LocalTableName"]));
            }
            set {
                this["LocalTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mod6MX")]
        public string LocalDBname {
            get {
                return ((string)(this["LocalDBname"]));
            }
            set {
                this["LocalDBname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcessFlowLog {
            get {
                return ((bool)(this["ProcessFlowLog"]));
            }
            set {
                this["ProcessFlowLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCloseLotErrors {
            get {
                return ((bool)(this["ShowCloseLotErrors"]));
            }
            set {
                this["ShowCloseLotErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.250.1")]
        public string PlcIP {
            get {
                return ((string)(this["PlcIP"]));
            }
            set {
                this["PlcIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string PortMarkLaser {
            get {
                return ((string)(this["PortMarkLaser"]));
            }
            set {
                this["PortMarkLaser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qsn.corp.sensata.com")]
        public string TraceabilityServerIP {
            get {
                return ((string)(this["TraceabilityServerIP"]));
            }
            set {
                this["TraceabilityServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mod68")]
        public string MachineName {
            get {
                return ((string)(this["MachineName"]));
            }
            set {
                this["MachineName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RomanShifts {
            get {
                return ((bool)(this["RomanShifts"]));
            }
            set {
                this["RomanShifts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChipLot {
            get {
                return ((string)(this["ChipLot"]));
            }
            set {
                this["ChipLot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartSN {
            get {
                return ((int)(this["StartSN"]));
            }
            set {
                this["StartSN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentSN {
            get {
                return ((int)(this["CurrentSN"]));
            }
            set {
                this["CurrentSN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Traceability {
            get {
                return ((bool)(this["Traceability"]));
            }
            set {
                this["Traceability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEndLotWindow {
            get {
                return ((bool)(this["ShowEndLotWindow"]));
            }
            set {
                this["ShowEndLotWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CameraOffset {
            get {
                return ((int)(this["CameraOffset"]));
            }
            set {
                this["CameraOffset"] = value;
            }
        }
    }
}
